### ISSUE TITLE
cfc-seed gives an error

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Legit-Info#68]
```
./stage1 loaddata sources/cfc-seed.json

**Using SQLite3**
Traceback (most recent call last):
  File "/home/theia/.local/share/virtualenvs/Legit-Info-_tFjoHw6/lib/python3.8/site-packages/django/core/serializers/json.py", line 69, in Deserializer
    objects = json.loads(stream_or_string)
  File "/usr/lib/python3.8/json/__init__.py", line 337, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 34, in <module>
    execute_from_command_line(sys.argv)
  File "/home/theia/.local/share/virtualenvs/Legit-Info-_tFjoHw6/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/theia/.local/share/virtualenvs/Legit-Info-_tFjoHw6/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/theia/.local/share/virtualenvs/Legit-Info-_tFjoHw6/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/theia/.local/share/virtualenvs/Legit-Info-_tFjoHw6/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/theia/.local/share/virtualenvs/Legit-Info-_tFjoHw6/lib/python3.8/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/home/theia/.local/share/virtualenvs/Legit-Info-_tFjoHw6/lib/python3.8/site-packages/django/core/management/commands/loaddata.py", line 114, in loaddata
    self.load_label(fixture_label)
  File "/home/theia/.local/share/virtualenvs/Legit-Info-_tFjoHw6/lib/python3.8/site-packages/django/core/management/commands/loaddata.py", line 172, in load_label
    for obj in objects:
  File "/home/theia/.local/share/virtualenvs/Legit-Info-_tFjoHw6/lib/python3.8/site-packages/django/core/serializers/json.py", line 74, in Deserializer
    raise DeserializationError() from exc
django.core.serializers.base.DeserializationError: Problem installing fixture '/home/project/Legit-Info/sources/cfc-seed.json'
```

**Comment by tonypearson** [comment]
Fixed as follows:
$ gedit sources/cfc-seed.json
select all,  copy, exit
$ gedit sources/cfc-seed2.json
paste, save
$ mv cfc-seed2.json cfc-seed.json

It is recommended to use "syncdata" instead of "loaddata", which handles pre-existing data.

./stage1  syncdata  sources/cfc-seed.json
./stage1  syncdata  sources/cfc-law30.json

**Comment by upkarlidder** [comment]
@tonypearson, I pulled the latest into the lab environment and still get a different error. Do I need to run the `gedit` steps locally in the lab environment? 

```
(Legit-Info) theia@theia-upkar:/home/project/Legit-Info$ ./stage1 syncdata sources/cfc-seed.json
**Using SQLite3**
Installing json fixture 'sources/cfc-seed' from absolute path.
CommandError: Problem installing fixture 'sources/cfc-seed.json': Traceback (most recent call last):
  File "/home/theia/.local/share/virtualenvs/Legit-Info-_tFjoHw6/lib/python3.8/site-packages/django/core/serializers/json.py", line 69, in Deserializer
    objects = json.loads(stream_or_string)
  File "/usr/lib/python3.8/json/__init__.py", line 337, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/theia/.local/share/virtualenvs/Legit-Info-_tFjoHw6/lib/python3.8/site-packages/django_extensions/management/commands/syncdata.py", line 165, in syncdata
    objects = list(serializers.deserialize(format_, fixture))
  File "/home/theia/.local/share/virtualenvs/Legit-Info-_tFjoHw6/lib/python3.8/site-packages/django/core/serializers/json.py", line 74, in Deserializer
    raise DeserializationError() from exc
django.core.serializers.base.DeserializationError
```

**Comment by tonypearson** [comment]
that's the same error.  Yes, try the gedit method.

**Comment by upkarlidder** [comment]
I had to save the file as `UTF-8 with BOM` in VS Code. Can I commit this back into the repo? It will be easier than asking each learner to take this step.

**Comment by tonypearson** [comment]
Yes, you can commit back to repo.

**Comment by upkarlidder** [comment]
Added https://github.com/Call-for-Code-for-Racial-Justice/Legit-Info/pull/69. Please review.
